name: Deploy to AWS

on:
  push:
    branches:
      - main  # Default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Change to your AWS region

    - name: Upload files to S3
      run: |
        aws s3 cp index.html s3://YOUR_BUCKET_NAME/
        aws s3 cp script.js s3://YOUR_BUCKET_NAME/
        aws s3 cp style.css s3://YOUR_BUCKET_NAME/

    - name: Update Lambda function
      run: |
        zip function.zip lambda.py
        aws lambda update-function-code --function-name YOUR_LAMBDA_FUNCTION_NAME --zip-file fileb://function.zip
